# Official docs:
# - https://docs.github.com/en/actions
# - https://github.com/actions

name: PyPI Release

on:
  push:
    tags:
      # - "v*" # only run on tags that start with 'v'
      - "[0-9]+.[0-9]+.[0-9]+" # matches tags in the format X.Y.Z

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # https://github.com/actions/setup-python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

      - name: Install dependencies
        run: poetry install --no-root

      - name: Build package
        run: poetry build

      # https://github.com/pypa/gh-action-pypi-publish
      # https://github.com/marketplace/actions/pypi-publish
      # https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
